[package]
name = "fable-rust-sample"
version = "0.1.0"
edition = "2021" 

[[bin]]
name = "program"
path = "Program.fs.rs"

[dependencies]
fable_library_rust = { path = "./fable_modules/fable-library-rust" }